// Записи реестра, слитые с каноническим брендом. Старые адреса ведут на канонический профиль,
// чтобы уже проиндексированные ссылки не превращались в 404.
export const mergedManufacturerSlugs: ReadonlyArray<{ from: string; to: string }> = [
  { from: "agie-charmilles", to: "agiecharmilles" },
  { from: "ari-stevi-comeval", to: "ari-armaturen" },
  { from: "aseptomag", to: "gea" },
  { from: "b-r-acopos", to: "br-automation" },
  { from: "berg", to: "berg-spanntechnik" },
  { from: "caryle", to: "carlyle-compressors" },
  { from: "ckd-group", to: "ckd" },
  { from: "coax", to: "co-ax-valves-inc" },
  { from: "coelmotori", to: "coel" },
  { from: "ebro", to: "ebro-armaturen" },
  { from: "elmo", to: "elmo-rietschle" },
  { from: "fenner", to: "fenner-drives" },
  { from: "franke", to: "franke-filter" },
  { from: "gamar", to: "sacemi-gamar" },
  { from: "getriebebau-nord", to: "nord" },
  { from: "giporec", to: "gipo" },
  { from: "jahns-hydraulik", to: "jahns-regulatoren" },
  { from: "jihostroy", to: "jihostroj" },
  { from: "kitagawa-america", to: "kitagawa-northtech" },
  { from: "konrad-reitz-ventilatoren", to: "reitz" },
  { from: "kromschroder", to: "elster-kromschroeder" },
  { from: "lapp-gmbh", to: "lapp-kabel" },
  { from: "macro-sensors", to: "amphenol-339272" },
  { from: "marathon-motors", to: "marathon-electric" },
  { from: "powerjacks", to: "power-jacks" },
  { from: "seybert-rahier", to: "sera" },
  { from: "southwest-oilfeld-products", to: "southwest-oilfield-products" },
  { from: "sunflo", to: "sundyne" },
  { from: "syntegon-technology", to: "bosch-packaging" },
  { from: "valsteam", to: "adca" },
  { from: "valtek", to: "flowserve" },
  { from: "verdermag", to: "verder" },
  { from: "weeke", to: "homag" },
  { from: "orsatti-motori", to: "ome-motors" },
  { from: "sew-usocome", to: "sew-eurodrive" },
  { from: "sirai", to: "asco-numatics" },
];
